// Bundles the ES modules in js/ into js/bundle.js, a classic script that also
// works when index.html is opened straight from disk (file://).
// Usage: node build.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const ORDER = ['icons', 'data', 'audio', 'rules', 'ai', 'combat', 'guide', 'main'];
const modName = (spec) => spec.replace(/^\.\//, '').replace(/\.js$/, '');

const parts = ORDER.map((name) => {
  let src = readFileSync(new URL(`./js/${name}.js`, import.meta.url), 'utf8');
  const exports = [];
  src = src
    .replace(/^import \* as (\w+) from '([^']+)';$/gm, (_, ns, spec) => `const ${ns} = __mods.${modName(spec)};`)
    .replace(/^import \{([^}]+)\} from '([^']+)';$/gm, (_, names, spec) => `const {${names}} = __mods.${modName(spec)};`)
    .replace(/^export (async function|function|class|const|let) (\w+)/gm, (_, kw, id) => {
      exports.push(id);
      return `${kw} ${id}`;
    });
  if (/^\s*(import|export)\b/m.test(src)) throw new Error(`Unhandled import/export syntax in js/${name}.js`);
  return `// ---- js/${name}.js ----\n__mods.${name} = (() => {\n${src}\nreturn { ${exports.join(', ')} };\n})();\n`;
});

const out = `// Generated by build.mjs — edit the files in js/ and rebuild instead of editing this.\n(() => {\n'use strict';\nconst __mods = {};\n${parts.join('\n')}})();\n`;
writeFileSync(new URL('./js/bundle.js', import.meta.url), out);
console.log(`Wrote js/bundle.js (${(out.length / 1024).toFixed(1)} KB)`);
